nginx:
  image: anguis/nginx:1.9.4
  entrypoint: /sbin/entrypoint.sh
  ports:
    - "80:80"
  volumes:
    - /Users/rustem/projects/docker-nginx/sites-enabled:/etc/nginx/sites-enabled
    - /Users/rustem/projects/docker-nginx/uploads:/uploads
  restart: always
